[package]
name = "mintbase-deps"
version = "0.1.0"
edition = "2018"
authors = [
    "evergreen-trading-systems <4870868+evergreen-trading-systems@users.noreply.github.com>",
]

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
clap = { version = "3.0.0-beta.2", optional = true }
near-sdk = { version = "4.0.0-pre.7", optional = true }
near-contract-standards = { version = "4.0.0-pre.7", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
store-wasm = ["wasm"]
factory-wasm = ["wasm"]
market-wasm = ["wasm"]
helper-wasm = ["wasm"]
test = ["clap", "all"]
all = ["wasm"]
wasm = ["near-sdk", "near-contract-standards"]
