[alias]
wasm = "build --target wasm32-unknown-unknown --release"
doc-all = "doc -p mintbase-deps --release --features store-wasm --features factory-wasm --lib --no-deps --target-dir mintbase-core-docs"
factory-wasm = "rustc -p mintbase-deps --release --features factory-wasm --target wasm32-unknown-unknown --lib -- --emit link=wasm/factory.wasm -C link-arg=-s -C opt-level=s -C codegen-units=1"
store-wasm = "rustc -p mintbase-deps --release --features store-wasm --target wasm32-unknown-unknown --lib -- --emit link=wasm/store.wasm -C link-arg=-s -C opt-level=s -C codegen-units=1"
market-wasm = "rustc -p simple-market-contract --release --target wasm32-unknown-unknown --lib -- --emit link=wasm/market.wasm -C link-arg=-s -C opt-level=s -C codegen-units=1"
helper-wasm = "rustc -p mintbase-deps --release --features helper-wasm --target wasm32-unknown-unknown --lib -- --emit link=wasm/helper.wasm -C link-arg=-s -C opt-level=s -C codegen-units=1"
indexer = "rustc -p mintbase-near-indexer --release --bin mintbase-near-indexer -- --emit link=bin/indexer"
stats = "rustc -p mintbase-near-indexer --release --bin stats -- --emit link=bin/stats"
lint = "clippy -- -D warnings"